name: eeregio
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip 
  - pandas 
  - pytest 
  - jupyter
  - notebook
  - pyogrio
  - openpyxl
  - black=22.3.0 
  - scikit-learn=1.3.2
  - xgboost 
  - matplotlib
  - gdal=3.4.2
  - geopandas
  - seaborn
  - cmcrameri